source "https://rubygems.org"

gem "bigdecimal"
gem "csv"
gem "jekyll", "~> 4.3"
gem "liquid", ">= 4.0.4", "< 5.0"
gem "just-the-docs"
gem "jekyll-relative-links"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
